package com.example.buildsrc

object Versions {
    const val mockk = "1.13.7"
    const val coroutinesTest = "1.2.1"
    const val coreKtx = "1.8.0"
    const val activityCompose = "1.5.1"
    const val composeUi = "1.2.1"
    const val composeMaterial = "1.2.1"
    const val composeAnimation = "1.2.1"
    const val composeUiTooling = "1.2.1"
    const val composeMaterialIconsExtended = "1.2.1"
    const val lifecycleRuntimeKtx = "2.5.1"
    const val coreSplashScreen = "1.0.0"
    const val navigationCompose = "2.5.1"
    const val lifecycleViewModelCompose = "2.5.1"
    const val lifecycleLiveDataKtx = "2.5.1"
    const val hiltAndroid = "2.48"
    const val material = "1.4.0"
    const val appcompat = "1.5.1"
    const val constraintlayout = "2.1.4"
    const val navigationFragmentKtx = "2.5.1"
    const val navigationUiKtx = "2.5.1"
    const val hiltNavigationCompose = "1.0.0"
    const val hiltCompiler = "2.48"
    const val firebaseBom = "30.3.2"
    const val firebaseUiAuth = "8.0.1"
    const val playServicesAuth = "20.7.0"
    const val datastorePreferences = "1.0.0"
    const val junit = "4.13.2"
    const val hiltAndroidTesting = "2.48"
    const val testExtJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val composeUiTestJunit4 = "1.5.3"
    const val composeUiTestManifest = "1.2.1"
}